/**
 * NEKUTOON — interacción y contenido
 * Para migrar a Cloudinary solo cambia las URL de MEDIA_CONFIG.
 * El resto de la interfaz consume claves y no necesita reescribir HTML.
 */
const MEDIA_CONFIG={
 hero:'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=1800&q=90',avatar:'https://i.pravatar.cc/96?img=47',
 fantasy:'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=900&q=85',action:'https://images.unsplash.com/photo-1541562232579-512a21360020?auto=format&fit=crop&w=900&q=85',romance:'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=900&q=85',isekai:'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=900&q=85',slice:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=85',comedy:'https://images.unsplash.com/photo-1614583225154-5fcdda07019e?auto=format&fit=crop&w=900&q=85',
 news1:'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&w=900&q=85',news2:'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=900&q=85',news3:'https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=900&q=85'
};
const manhwas=[
 {id:'shadow-hunter',title:'El Cazador de Sombras',meta:'Fantasía • 49 capítulos',score:'4.9',isNew:true,image:MEDIA_CONFIG.action},{id:'eternal-legend',title:'Eternal Legend',meta:'Acción • 72 capítulos',score:'4.8',image:'https://images.unsplash.com/photo-1614583225154-5fcdda07019e?auto=format&fit=crop&w=600&q=85'},{id:'crimson-heiress',title:'La Heredera Carmesí',meta:'Romance • 38 capítulos',score:'4.7',isNew:true,image:MEDIA_CONFIG.romance},{id:'northern-ashes',title:'Cenizas del Norte',meta:'Drama • 61 capítulos',score:'4.8',image:MEDIA_CONFIG.isekai},{id:'infinite-tower',title:'La Torre Infinita',meta:'Aventura • 106 capítulos',score:'4.9',isNew:true,image:'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=600&q=85'},{id:'arcane-code',title:'Código Arcano',meta:'Misterio • 28 capítulos',score:'4.6',image:MEDIA_CONFIG.slice},{id:'crystal-night',title:'Noche de Cristal',meta:'Fantasía • 43 capítulos',score:'4.7',isNew:true,image:MEDIA_CONFIG.fantasy},{id:'last-guardian',title:'El Último Guardián',meta:'Acción • 84 capítulos',score:'4.8',image:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=600&q=85'}
];
const trends=[{title:'Solo Leveling',genre:'Acción • Fantasía',image:manhwas[0].image},{title:'Omniscient Reader',genre:'Aventura • Drama',image:manhwas[1].image},{title:'Villains Are Destined to Die',genre:'Romance • Isekai',image:manhwas[2].image},{title:'Tower of God',genre:'Fantasía • Misterio',image:manhwas[4].image},{title:'The World After the Fall',genre:'Acción • Aventura',image:manhwas[6].image}];
const reviews=[{user:'Luna.art',text:'Una construcción de mundo increíble. Cada capítulo mejora al anterior.',work:'El Cazador de Sombras',likes:82,avatar:'https://i.pravatar.cc/96?img=47'},{user:'DaniReads',text:'La evolución del protagonista está muy bien escrita y el arte es espectacular.',work:'Eternal Legend',likes:64,avatar:'https://i.pravatar.cc/96?img=12'},{user:'Mika_07',text:'Necesito la próxima temporada ya. El final me dejó sin palabras.',work:'La Heredera Carmesí',likes:51,avatar:'https://i.pravatar.cc/96?img=32'}];
const categories=[['Fantasía','fantasy'],['Acción','action'],['Romance','romance'],['Isekai','isekai'],['Recuentos de la vida','slice'],['Comedia','comedy']];
const news=[{label:'Novedades',title:'Los estrenos de manhwa que no puedes perderte este mes',date:'18 Sep 2026',comments:24,image:'news1'},{label:'Guías',title:'Cómo empezar a leer webtoons: guía esencial para nuevos lectores',date:'15 Sep 2026',comments:18,image:'news2'},{label:'Comunidad',title:'Las historias mejor valoradas por la comunidad de Nekutoon',date:'12 Sep 2026',comments:37,image:'news3'}];

/* Inyección global de imágenes declaradas mediante data-media-key. */
document.querySelectorAll('[data-media-key]').forEach(el=>{const url=MEDIA_CONFIG[el.dataset.mediaKey];if(url)el.src=url});
const track=document.getElementById('cardsTrack');
track.innerHTML=manhwas.map(item=>`<article class="media-card" tabindex="0" data-title="${item.title}"><div class="cover"><img src="${item.image}" alt="Portada de ${item.title}" loading="lazy"><span class="card-badge score"><i data-lucide="star"></i>${item.score}</span>${item.isNew?'<span class="card-badge new">Nuevo</span>':''}<button class="card-favorite favorite-toggle" type="button" data-favorite-id="${item.id}" aria-label="Añadir ${item.title} a favoritos"><i data-lucide="heart"></i></button></div><div class="card-info"><h3 class="card-title">${item.title}</h3><p class="card-meta">${item.meta}</p></div></article>`).join('');
document.getElementById('trendingList').innerHTML=trends.map((item,i)=>`<li class="rank-item"><span class="rank-number">${i+1}</span><img class="rank-thumb" src="${item.image}" alt="Portada de ${item.title}" loading="lazy"><div class="rank-copy"><h3 class="rank-name">${item.title}</h3><p class="rank-genre">${item.genre}</p></div><span class="trend-up"><i data-lucide="trending-up"></i></span></li>`).join('');
document.getElementById('reviewsList').innerHTML=reviews.map(item=>`<article class="review-item"><img class="review-avatar" src="${item.avatar}" alt="Avatar de ${item.user}" loading="lazy"><div class="review-main"><div class="review-head"><span class="review-user">${item.user}</span><span class="review-stars">${'<i data-lucide="star"></i>'.repeat(5)}</span></div><p class="review-text">“${item.text}”</p><p class="review-work">${item.work}</p></div><button class="review-like" type="button" data-likes="${item.likes}" aria-label="Me gusta"><i data-lucide="heart"></i><span>${item.likes}</span></button></article>`).join('');
document.getElementById('categoriesGrid').innerHTML=categories.map(([name,key])=>`<a href="#recomendados" class="category-card" data-category="${name}"><img src="${MEDIA_CONFIG[key]}" alt="Categoría ${name}" loading="lazy"><h3>${name}</h3></a>`).join('');
document.getElementById('newsGrid').innerHTML=news.map(item=>`<article class="news-card"><div class="news-media"><img src="${MEDIA_CONFIG[item.image]}" alt="${item.title}" loading="lazy"><span class="news-label">${item.label}</span></div><div class="news-body"><h3>${item.title}</h3><div class="news-meta"><span><i data-lucide="calendar-days"></i>${item.date}</span><span><i data-lucide="message-circle"></i>${item.comments}</span></div></div></article>`).join('');
function refreshIcons(){lucide.createIcons({attrs:{'stroke-width':1.8}})}refreshIcons();

/* Avisos discretos para acciones de demostración. */
const toast=document.getElementById('toast');let toastTimer;function showToast(message){clearTimeout(toastTimer);toast.textContent=message;toast.classList.add('show');toastTimer=setTimeout(()=>toast.classList.remove('show'),1800)}

/* Favoritos persistentes con localStorage. */
const FAVORITES_KEY='nekutoon:favorites';
function getFavorites(){try{return new Set(JSON.parse(localStorage.getItem(FAVORITES_KEY)||'[]'))}catch{return new Set()}}
function saveFavorites(set){localStorage.setItem(FAVORITES_KEY,JSON.stringify([...set]))}
function paintFavorites(){const saved=getFavorites();document.querySelectorAll('[data-favorite-id]').forEach(btn=>{const active=saved.has(btn.dataset.favoriteId);btn.classList.toggle('active',active);btn.setAttribute('aria-pressed',String(active))})}
document.addEventListener('click',event=>{const btn=event.target.closest('[data-favorite-id]');if(!btn)return;event.preventDefault();event.stopPropagation();const favorites=getFavorites(),id=btn.dataset.favoriteId;if(favorites.has(id)){favorites.delete(id);showToast('Eliminado de favoritos')}else{favorites.add(id);showToast('Añadido a favoritos')}saveFavorites(favorites);paintFavorites()});paintFavorites();

/* Campana y menú de tres notificaciones. */
const notificationBtn=document.getElementById('notificationBtn'),notificationDropdown=document.getElementById('notificationDropdown'),notificationBadge=document.getElementById('notificationBadge');
function closeNotifications(){notificationDropdown.classList.remove('open');notificationDropdown.setAttribute('aria-hidden','true');notificationBtn.setAttribute('aria-expanded','false')}
notificationBtn.addEventListener('click',event=>{event.stopPropagation();const open=notificationDropdown.classList.toggle('open');notificationDropdown.setAttribute('aria-hidden',String(!open));notificationBtn.setAttribute('aria-expanded',String(open))});
document.getElementById('markReadBtn').addEventListener('click',()=>{notificationBadge.classList.add('hidden');notificationBtn.setAttribute('aria-label','Sin notificaciones nuevas');showToast('Notificaciones marcadas como leídas')});
document.addEventListener('click',event=>{if(!event.target.closest('.notification-wrap'))closeNotifications()});document.addEventListener('keydown',event=>{if(event.key==='Escape')closeNotifications()});

/* Buscador: registra la consulta en la consola al pulsar Enter. */
document.querySelectorAll('.search-input').forEach(input=>input.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();const query=input.value.trim();if(query){console.log('[Nekutoon búsqueda]:',query);showToast(`Buscando “${query}”`)}}}));

/* Validación del boletín sin recargar la página. */
const newsletterForm=document.getElementById('newsletterForm'),emailInput=document.getElementById('emailInput'),subscribeBtn=document.getElementById('subscribeBtn'),newsletterMessage=document.getElementById('newsletterMessage');
newsletterForm.addEventListener('submit',event=>{event.preventDefault();const email=emailInput.value.trim(),valid=/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(email);emailInput.classList.toggle('invalid',!valid);newsletterMessage.classList.toggle('success',valid);if(!valid){newsletterMessage.textContent='Introduce un correo electrónico válido.';emailInput.focus();return}newsletterMessage.textContent='¡Gracias por suscribirte!';const original=subscribeBtn.textContent;subscribeBtn.textContent='¡Suscrito!';subscribeBtn.classList.add('success');subscribeBtn.disabled=true;emailInput.value='';setTimeout(()=>{subscribeBtn.textContent=original;subscribeBtn.classList.remove('success');subscribeBtn.disabled=false;newsletterMessage.textContent=''},3000)});

/* Navegación móvil y carrusel. */
const menuBtn=document.getElementById('menuBtn'),mobileNav=document.getElementById('mobileNav');menuBtn.addEventListener('click',()=>{const open=mobileNav.classList.toggle('open');menuBtn.setAttribute('aria-expanded',open);menuBtn.innerHTML=`<i data-lucide="${open?'x':'menu'}"></i>`;refreshIcons()});
const mobileSearch=document.getElementById('mobileSearch');document.getElementById('mobileSearchBtn').addEventListener('click',()=>{mobileSearch.classList.toggle('visible');if(mobileSearch.classList.contains('visible'))document.getElementById('mobileSearchInput').focus()});
let cardPage=0;const prev=document.getElementById('cardsPrev'),next=document.getElementById('cardsNext');function visibleCards(){return innerWidth<=760?2:innerWidth<=1230?5:6}function updateCarousel(){if(innerWidth<=760){track.style.transform='';prev.disabled=true;next.disabled=true;return}const max=Math.max(0,manhwas.length-visibleCards());cardPage=Math.min(cardPage,max);const card=track.querySelector('.media-card'),step=card?card.getBoundingClientRect().width+10:0;track.style.transform=`translateX(${-cardPage*step}px)`;prev.disabled=cardPage===0;next.disabled=cardPage>=max}prev.addEventListener('click',()=>{cardPage=Math.max(0,cardPage-1);updateCarousel()});next.addEventListener('click',()=>{cardPage++;updateCarousel()});addEventListener('resize',updateCarousel);updateCarousel();

/* Acciones generales y pequeños estados visuales. */
document.addEventListener('click',event=>{const action=event.target.closest('[data-action]');if(action){event.preventDefault();showToast(action.dataset.action)}const card=event.target.closest('.media-card');if(card&&!event.target.closest('.card-favorite'))showToast(`Abriendo ${card.dataset.title}`);const category=event.target.closest('[data-category]');if(category)showToast(`Explorando ${category.dataset.category}`);const dot=event.target.closest('.slider-dots button');if(dot){document.querySelectorAll('.slider-dots button').forEach(el=>el.classList.remove('active'));dot.classList.add('active')}});document.querySelectorAll('.review-like').forEach(button=>button.addEventListener('click',()=>{const active=button.classList.toggle('liked'),base=Number(button.dataset.likes);button.querySelector('span').textContent=base+(active?1:0)}));